name: Trigger auto deployment for container-app-64cg7iyviwmnq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-64cg7iyviwmnq-AutoDeployTrigger-1390b7c8-b1f5-43db-8734-796398e1c7b1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP64CG7IYVIWMNQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP64CG7IYVIWMNQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP64CG7IYVIWMNQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP64CG7IYVIWMNQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP64CG7IYVIWMNQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-64cg7iyviwmnq
          resourceGroup: todoappspaceabae
          imageToBuild: default/container-app-64cg7iyviwmnq:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


